[package]
name = "apptalk_client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
futures = "0.3.31"
ratatui = "0.29.0"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
tui-textarea = "0.7.0"
